### ISSUE TITLE
Patool `oops I did it again` error

### ISSUE THREAD

**Issue by NatanFreeman** [wummel/patool#121]
I believe the issue has something to do with invalid Unicode on Windows which some of my files appear to have.
>********** Oops, I did it again. *************

>You have found an internal error in patool. Please write a bug report
at https://github.com/wummel/patool/issues/ and include at least the information below:

>Not disclosing some of the information below due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

><class 'UnicodeEncodeError'> 'charmap' codec can't encode characters in position 40-43: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\Natan\AppData\Local\pypoetry\Cache\virtualenvs\aigrader-JJoG15ws-py3.10\Scripts\patool", line 213, in main
    res = globals()["run_%s" % args.command](args)
  File "C:\Users\Natan\AppData\Local\pypoetry\Cache\virtualenvs\aigrader-JJoG15ws-py3.10\Scripts\patool", line 33, in run_extract
    patoolib.extract_archive(archive, verbosity=args.verbosity, interactive=args.interactive, outdir=args.outdir)
  File "C:\Users\Natan\AppData\Local\pypoetry\Cache\virtualenvs\aigrader-JJoG15ws-py3.10\lib\site-packages\patoolib\__init__.py", line 683, in extract_archive
    util.log_info("Extracting %s ..." % archive)
  File "C:\Users\Natan\AppData\Local\pypoetry\Cache\virtualenvs\aigrader-JJoG15ws-py3.10\lib\site-packages\patoolib\util.py", line 516, in log_info
    print("patool:", msg, file=out)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 40-43: character maps to <undefined>
System info:
patool 1.12
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Local time: 2022-12-22 21:42:09+003
sys.argv ['C:\\Users\\Natan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\aigrader-JJoG15ws-py3.10\\Scripts\\patool', '--non-interactive', 'extract', ```[REMOVED FOR PRIVACY]```]

 >******** patool internal error, over and out ********

**Comment by wummel** [comment]
A new version 1.14.1 of patool has been released on
26.10.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
