### ISSUE TITLE
file "x" was not found

### ISSUE THREAD

**Issue by timthurner** [wummel/patool#123]
import patoolib
>>> patoolib.create_archive("file.7z", "/tmp/b98db6e2-a462-4fd7-afeb-9a153c28e0b9", verbosity=1)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/patoolib/__init__.py", line 794, in create_archive
    util.check_archive_filelist(filenames)
  File "/usr/local/lib/python3.10/dist-packages/patoolib/util.py", line 426, in check_archive_filelist
    check_existing_filename(filename, onlyfiles=False)
  File "/usr/local/lib/python3.10/dist-packages/patoolib/util.py", line 402, in check_existing_filename
    raise PatoolError("file `%s' was not found" % filename)
patoolib.util.PatoolError: file `t' was not found

am i doing something wrong here is there any pre-requisite on how to supply directory path for creating an archive ?

**Comment by timthurner** [comment]
apologies closing the issue sorted by enclosing the path in a list instead
