### ISSUE TITLE
patoolib can't handle "no console" Scripts

### ISSUE THREAD

**Issue by H1ghSyst3m** [wummel/patool#158]
When Compiling a Script with any compile like pyinstaller as a windowed (no console)

Then the .exe crashes right away with the error:
```
Traceback (most recent call last):
  File "MainScript.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "Assets\Modules\FileCreator.py", line 21, in <module>
    import patoolib
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "patoolib\__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "patoolib\fileutil.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "patoolib\log.py", line 40, in <module>
AttributeError: 'NoneType' object has no attribute 'encoding'
```

The Problem is, because the Script has no console, patoolib can't handle when there is `sys.stderr  None`

Here is the code area:  https://github.com/wummel/patool/blob/4c43466eb0b8895eb48c3406fa3b6d93a06dfc85/patoolib/log.py#L40

**Comment by wummel** [comment]
A new version 2.3.0 of patool has been released on
26.06.2024.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
