### ISSUE TITLE
pyunpack not working from cron (python3)

### ISSUE THREAD

**Issue by Zeka13** [wummel/patool#48]
Works from manual start, not working from crontab

**patool: error: unrecognized arguments: --non-interactive**
`Traceback (most recent call last):
  File "/opt/ip_location/ip_location.py", line 183, in <module>
    main()
  File "/opt/ip_location/ip_location.py", line 91, in main
    Archive(curDownloadedBase).extractall(temporaryDir)
  File "/usr/local/lib/python3.4/dist-packages/pyunpack/__init__.py", line 90, in extractall
    self.extractall_patool(directory, patool_path)
  File "/usr/local/lib/python3.4/dist-packages/pyunpack/__init__.py", line 62, in extractall_patool
    raise PatoolError('patool can not unpack\n' + str(p.stderr))
pyunpack.PatoolError: patool can not unpack
usage: patool [-h] [--verbose]
              {extract,list,create,test,repack,diff,search,formats} ...
patool: error: unrecognized arguments: --non-interactive
`

**Comment by Zeka13** [comment]
fixed with
`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
