### ISSUE TITLE
Not extracting archives with Japanese names

### ISSUE THREAD

**Issue by SelaO** [wummel/patool#52]
I'm getting the following error on files with Japanese characters.

Here are examples of the names that cause these errors: 

>(C86) [C-CLAYS] - 番ヒノ翼 -ツガヒノツバサ-.7z
>(C92) 幽閉 少女 ア ク テ ィ ブ NEETs - 第 3 幕 協奏曲 「華 鳥 風月」 SIDE B [KNCD-0015].rar

If I change the names of these archives to `a.7z` then no error happen, but the name of the folders is crucial for my script. Is there any way to fix this?

I can send you these archives if you want. 

```
error: patool can not unpack


********** Oops, I did it again. *************

You have found an internal error in patool. Please write a bug report
at https://github.com/wummel/patool/issues/ and include at least the information below:

Not disclosing some of the information below due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

<class 'UnicodeEncodeError'> 'charmap' codec can't encode characters in position 47-50: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\S\AppData\Local\Programs\Python\Python36-32\Scripts\patool", line 213, in main
    res = globals()["run_%s" % args.command](args)
  File "C:\Users\S\AppData\Local\Programs\Python\Python36-32\Scripts\patool", line 33, in run_extract
    patoolib.extract_archive(archive, verbosity=args.verbosity, interactive=args.interactive, outdir=args.outdir)
  File "C:\Users\S\AppData\Local\Programs\Python\Python36-32\lib\site-packages\patoolib\__init__.py", line 683, in extract_archive
    util.log_info("Extracting %s ..." % archive)
  File "C:\Users\S\AppData\Local\Programs\Python\Python36-32\lib\site-packages\patoolib\util.py", line 516, in log_info
    print("patool:", msg, file=out)
  File "C:\Users\S\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 47-50: character maps to <undefined>
System info:
patool 1.12
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Local time: 2017-12-23 17:25:54+003
sys.argv ['C:\\Users\\S\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\patool', '--non-interactive', 'extract', 'D:\\New folder (2)\\(C86) [C-CLAYS] - \u756a\u
30d2\u30ce\u7ffc -\u30c4\u30ac\u30d2\u30ce\u30c4\u30d0\u30b5-.7z', '--outdir=D:\\New folder (2)\\tmp']
LANG = 'en_US.UTF-8'

 ******** patool internal error, over and out ********
error: patool can not unpack


********** Oops, I did it again. *************

You have found an internal error in patool. Please write a bug report
at https://github.com/wummel/patool/issues/ and include at least the information below:

Not disclosing some of the information below due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

<class 'UnicodeEncodeError'> 'charmap' codec can't encode characters in position 35-36: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\S\AppData\Local\Programs\Python\Python36-32\Scripts\patool", line 213, in main
    res = globals()["run_%s" % args.command](args)
  File "C:\Users\S\AppData\Local\Programs\Python\Python36-32\Scripts\patool", line 33, in run_extract
    patoolib.extract_archive(archive, verbosity=args.verbosity, interactive=args.interactive, outdir=args.outdir)
  File "C:\Users\S\AppData\Local\Programs\Python\Python36-32\lib\site-packages\patoolib\__init__.py", line 683, in extract_archive
    util.log_info("Extracting %s ..." % archive)
  File "C:\Users\S\AppData\Local\Programs\Python\Python36-32\lib\site-packages\patoolib\util.py", line 516, in log_info
    print("patool:", msg, file=out)
  File "C:\Users\S\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 35-36: character maps to <undefined>
System info:
patool 1.12
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Local time: 2017-12-23 17:25:54+003
sys.argv ['C:\\Users\\S\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\patool', '--non-interactive', 'extract', 'D:\\New folder (2)\\(C92) \u5e7d\u9589 \u5c11\
u5973 \u30a2 \u30af \u30c6 \u30a3 \u30d6 NEETs - \u7b2c 3 \u5e55 \u5354\u594f\u66f2 \u300c\u83ef \u9ce5 \u98a8\u6708\u300d SIDE B [KNCD-0015].rar', '--outdir=D:\\New fol
der (2)\\tmp']
LANG = 'en_US.UTF-8'

 ******** patool internal error, over and out ********
PS D:\New folder (2)>
```

**Comment by cledoux** [comment]
Can you provide example scripts that replicate error?  I'm having a similar issue, but can't seem to replicate on a file that I can share (the file causing the error contains sensitive information and thus cannot be shared).

**Comment by SelaO** [comment]
Make an empty (or with some files) 7z archive with one of the names I gave.

Here's a minimal script where it happens.

```
import os
import shutil
from pyunpack import Archive

tmpFolder = './tmp/'
shutil.rmtree(tmpFolder, True)

files = [f for f in os.listdir('.') if os.path.isfile(f) and (
    f.endswith('.7z') or f.endswith('.zip') or f.endswith('.rar')
)]

for filename in files:
    try:
        Archive(filename).extractall(tmpFolder, True)
    except Exception as e:
        print("error: " + str(e))
    shutil.rmtree(tmpFolder, True)
    continue
	
```

**Comment by cledoux** [comment]
It fails to replicate on my system. I'm on Ubuntu 16.04 and used both python 2.7 and python 3.5.  It works whether I use to script you provided or use `patool` from the command line.  Replication steps below.

If I get some time later, I might see if I can replicate on Windows to help you out. It'll require digging a VM out, though, as I don't have any windows machines handy.

Not sure if it matters, but which version of Windows are you running?

```
>>> echo "(C86) [C-CLAYS] - 番ヒノ翼 -ツガヒノツバサ-.7z" > text
>>> 7z a "(C86) [C-CLAYS] - 番ヒノ翼 -ツガヒノツバサ-.7z" text
>>>  patool extract "(C86) [C-CLAYS] - 番ヒノ翼 -ツガヒノツバサ-.7z"
patool: Extracting (C86) [C-CLAYS] - 番ヒノ翼 -ツガヒノツバサ-.7z ...
patool: running /usr/bin/7z x -o./Unpack_qdcJs2 -- "(C86) [C-CLAYS] - 番ヒノ翼 -ツガヒノツバサ-.7z"
patool: ... (C86) [C-CLAYS] - 番ヒノ翼 -ツガヒノツバサ-.7z extracted to `(C86) [C-CLAYS] - 番ヒノ翼 -ツガヒノツバサ-' (local file exists).
```

```
>>> echo "(C92) 幽閉 少女 ア ク テ ィ ブ NEETs - 第 3 幕 協奏曲 「華 鳥 風月」 SIDE B [KNCD-0015].rar" > text
>>> 7z a "(C92) 幽閉 少女 ア ク テ ィ ブ NEETs - 第 3 幕 協奏曲 「華 鳥 風月」 SIDE B [KNCD-0015].rar" text
>>> patool extract "(C92) 幽閉 少女 ア ク テ ィ ブ NEETs - 第 3 幕 協奏曲 「華 鳥 風月」 SIDE B [KNCD-0015].rar"
patool: Extracting (C92) 幽閉 少女 ア ク テ ィ ブ NEETs - 第 3 幕 協奏曲 「華 鳥 風月」 SIDE B [KNCD-0015].rar ...
patool: running /usr/bin/7z x -o./Unpack_lPBosM -- "(C92) 幽閉 少女 ア ク テ ィ ブ NEETs - 第 3 幕 協奏曲 「華 鳥 風月」 SIDE B [KNCD-0015].rar"
patool: ... (C92) 幽閉 少女 ア ク テ ィ ブ NEETs - 第 3 幕 協奏曲 「華 鳥 風月」 SIDE B [KNCD-0015].rar extracted to `(C92) 幽閉 少女 ア ク テ ィ ブ NEETs - 第 3 幕 協奏曲 「華 鳥 風月」 SIDE B [KNCD-0015]' (local file exists).
```

This works for both python 2.7 and python 3.5.

**Comment by SelaO** [comment]
I'm on python 3.6.4, win 10 64b.

Did the archives you made had files in? That's the settings I used to make the 7zs: 

![image](https://user-images.githubusercontent.com/21977571/34416259-5cbeff64-ebfb-11e7-8a41-8b62dc3be838.png)

And here's a file that it happens with: 
https://mega.nz/#!AZQHTTwR!fc7MDhjIflbTIhNxIjK9jHrPt2iwYbCVdZGi5g29w3o

**Comment by cledoux** [comment]
The file you provided extracts just fine on Ubuntu.

I used docker to test on python3.6 and it still works just fine.

My guess is that it's a Windows specific bug that will require Windows to replicate.

**Comment by dset0x** [comment]
It's likely that you're looking for
```
UNZIP="-O cp932" unzip *.zip
```

**Comment by SelaO** [comment]
I want to extract everything that 7zip can extract not just zip.

**Comment by wummel** [comment]
A new version 1.14.1 of patool has been released on
26.10.2023.
Therefore this bug will be closed. If you think this issue is not solved,
please open a new issue.
