### ISSUE TITLE
decode fails on gzip archive of already zipped file

### ISSUE THREAD

**Issue by falon** [wummel/patool#76]
Hello,

 let suppose to zip a file with `zip` and then with `gzip`:

`$ zip test.zip file.txt`
`$ gzip test.zip`
`$ ls`
`test.zip.gz`

`$ cat prova.py`
```
import patoolib
patoolib.test_archive("test.zip.gz", verbosity=1)
```

If I run prova.py the decode fails:
`$ python3 test.py`
```
patool: Testing test.zip.gz ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patoolib/programs/py_zipfile.py", line 28, in list_zip
    with zipfile.ZipFile(archive, "r") as zfile:
  File "/usr/lib64/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib64/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prova.py", line 4, in <module>
    patoolib.test_archive("test.zip.gz", verbosity=1)
  File "/usr/local/lib/python3.6/site-packages/patoolib/__init__.py", line 703, in test_archive
    interactive=interactive, program=program)
  File "/usr/local/lib/python3.6/site-packages/patoolib/__init__.py", line 538, in _handle_archive
    cmdlist = get_archive_cmdlist(archive, compression, program, verbosity, interactive)
  File "/usr/local/lib/python3.6/site-packages/patoolib/programs/py_zipfile.py", line 34, in list_zip
    raise util.PatoolError(msg)
patoolib.util.PatoolError: error listing test.zip.gz: File is not a zip file
```

The decode runs with success if the gzip file doesn't contains already compressed files with zip.

`$ gzip -V`
```
gzip 1.5
Copyright (C) 2007, 2010, 2011 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

Written by Jean-loup Gailly.
```

**Comment by parona-source** [comment]
I tried to reproduce but couldnt, tested current HEAD and the tagged 1.12. With lack of mentioned patool version it could either be that is a bug in an older release meaning this should be closed, or is related to the older python version as im using python3.11.

```
ask@bigglane /home/ask
 $ echo "test data" > test
ask@bigglane /home/ask
 $ zip test.zip test
  adding: test (stored 0%)
ask@bigglane /home/ask
 $ gzip test.zip
ask@bigglane /home/ask
 $ python -c "import patoolib; patoolib.test_archive('test.zip.gz', verbosity=1)"
patool: Testing test.zip.gz ...
patool: running /usr/bin/7z t -- test.zip.gz

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_GB.utf8,Utf16=on,HugeFiles=on,64 bits,32 CPUs AMD Ryzen 5 3600 6-Core Processor               (870F10),ASM,AES-NI)

Scanning the drive for archives:
1 file, 127 bytes (1 KiB)

Testing archive: test.zip.gz
--
Path = test.zip.gz
Type = gzip
Headers Size = 19

Everything is Ok

Size:       168
Compressed: 127
patool: ... tested ok.
```

**Comment by wummel** [comment]
In your case, patool did not correctly detect the .gz file format. But this is not reproducible on my test systems. If the error is still there in the current release please file a new bug.
