### ISSUE TITLE
ModuleNotFoundError: No module named 'patoolib'

### ISSUE THREAD

**Issue by logm1lo** [wummel/patool#97]
C:\Users\Admin\Desktop\video2x-master\src>python video2x_setup.py
Video2X Setup Script
Version: 2.4.1

Installing Python libraries
C:\Users\Admin\AppData\Local\Programs\Python\Python39\python.exe: No module named pip

Installing FFmpeg
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\video2x-master\src\video2x_setup.py", line 475, in <module>
    setup.run()
  File "C:\Users\Admin\Desktop\video2x-master\src\video2x_setup.py", line 110, in run
    getattr(self, f"_install_{driver}")()
  File "C:\Users\Admin\Desktop\video2x-master\src\video2x_setup.py", line 142, in _install_ffmpeg
    import patoolib
ModuleNotFoundError: No module named 'patoolib'
An error has occurred
Video2X Automatic Setup has failed

Cleaning up temporary files
Script finished
Time taken: 0:00:00

**Comment by jalotra** [comment]
Just do : `pip install patoolib`

**Comment by wummel** [comment]
Use `pip install patool` to make patoolib available. The video2x program should add this to its requirements.
